name: CI - sample API

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ci:
    uses: stevenhart235-dev/platform-workflows/.github/workflows/reusable-python-ci.yml@v1.0.0
